[general]
bars = 4
framerate = 30

[input]
method = pulse
source = auto
channels = mono

[smoothing]
monstercat = 1
noise_reduction = 0.77
autosens = 0
sensitivity = 15

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100
bar_delimiter = 59
frame_delimiter = 10
